"""Pydantic input models for Yandex MCP Server."""

from yandex_mcp.models.common import StrictModel
from yandex_mcp.models.direct import (
    AddKeywordsInput,
    CreateAdGroupInput,
    CreateCampaignInput,
    CreateTextAdInput,
    DeleteImagesInput,
    DirectReportInput,
    GetAdGroupsInput,
    GetAdsInput,
    GetCampaignsInput,
    GetImagesInput,
    GetKeywordsInput,
    KeywordBidItem,
    ManageAdInput,
    ManageCampaignInput,
    ManageKeywordInput,
    SetKeywordBidsInput,
    UpdateAdGroupInput,
    UpdateCampaignInput,
    UpdateTextAdInput,
    UploadImageInput,
)
from yandex_mcp.models.metrika import (
    CreateCounterInput,
    CreateGoalInput,
    DeleteCounterInput,
    GetCounterInput,
    GetCountersInput,
    GetGoalsInput,
    GoalCondition,
    MetrikaByTimeInput,
    MetrikaReportInput,
)
from yandex_mcp.models.wordstat import (
    WordstatDynamicsInput,
    WordstatRegionsInput,
    WordstatRegionsTreeInput,
    WordstatTopRequestsInput,
    WordstatUserInfoInput,
)

__all__ = [
    "StrictModel",
    "AddKeywordsInput",
    "CreateAdGroupInput",
    "CreateCampaignInput",
    "CreateTextAdInput",
    "DeleteImagesInput",
    "DirectReportInput",
    "GetAdGroupsInput",
    "GetAdsInput",
    "GetCampaignsInput",
    "GetImagesInput",
    "GetKeywordsInput",
    "KeywordBidItem",
    "ManageAdInput",
    "ManageCampaignInput",
    "ManageKeywordInput",
    "SetKeywordBidsInput",
    "UpdateAdGroupInput",
    "UpdateCampaignInput",
    "UpdateTextAdInput",
    "UploadImageInput",
    "CreateCounterInput",
    "CreateGoalInput",
    "DeleteCounterInput",
    "GetCounterInput",
    "GetCountersInput",
    "GetGoalsInput",
    "GoalCondition",
    "MetrikaByTimeInput",
    "MetrikaReportInput",
    "WordstatDynamicsInput",
    "WordstatRegionsInput",
    "WordstatRegionsTreeInput",
    "WordstatTopRequestsInput",
    "WordstatUserInfoInput",
]
